import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Trading Research Agent",
  description:
    "Cited, verifiable equity research reports generated by an open-source deep research agent.",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
