"""The report contract.

This module is the **single source of truth for the shape of a research report**.
The agent must produce it; the API serves it; the web UI renders it; the eval
suite grades it. Change it here and everything else follows.

Two invariants are enforced by the schema itself, not by convention:

1. **No dangling citations.** Every ``source_id`` referenced by a claim or a
   metric series must exist in ``Report.sources``. A model that invents a
   citation fails validation instead of shipping a plausible-looking lie.
2. **No uncited claims.** Every :class:`Claim` carries at least one source.
   If the agent cannot attribute a statement, it does not belong in the report.

Regenerate the machine-readable artifacts after any change here::

    make schema
"""

from __future__ import annotations

import hashlib
import json
from enum import StrEnum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, model_validator

SCHEMA_VERSION = "0.1.0"

DISCLAIMER = (
    "This report is generated by an automated research agent for informational "
    "purposes only. It is not investment advice, and it contains no rating, "
    "recommendation or price target. Data may be delayed or incomplete. "
    "Verify every figure against the linked primary source before acting on it."
)

Confidence = Literal["high", "medium", "low"]


class SourceKind(StrEnum):
    """Where a piece of evidence came from. Drives the citation UI's icon and styling."""

    SEC_FILING = "sec_filing"
    MARKET_DATA = "market_data"
    WEB = "web"
    COMPUTED = "computed"
    """Derived locally in Python (a growth rate, a margin). Never produced by the model."""


class SectionKind(StrEnum):
    """The fixed report skeleton. See docs/design.md section 1.2."""

    SUMMARY = "summary"
    BUSINESS = "business"
    FINANCIALS = "financials"
    VALUATION = "valuation"
    CATALYSTS = "catalysts"
    BULL_BEAR = "bull_bear"
    RISKS = "risks"


def make_source_id(url: str, locator: str | None = None) -> str:
    """Deterministic 10-char id, so the same evidence always gets the same id.

    Determinism matters: it makes reports diffable across runs and lets the
    eval suite compare citations without fuzzy matching.
    """
    digest = hashlib.sha1(f"{url}#{locator or ''}".encode()).hexdigest()
    return digest[:10]


class Source(BaseModel):
    """One piece of evidence, precise enough for a reader to land on the exact passage."""

    id: str = Field(pattern=r"^[0-9a-f]{10}$", description="See make_source_id()")
    kind: SourceKind
    title: str
    url: str
    locator: str | None = Field(
        default=None,
        description="Where inside the source, e.g. '10-K FY2025, Item 1A, para 12'",
    )
    snippet: str = Field(
        default="",
        max_length=2000,
        description="Verbatim excerpt backing the claim. Never the full document — "
        "full text lives in the cache layer, not in the report or the graph state.",
    )
    published_at: AwareDatetime | None = None
    retrieved_at: AwareDatetime


class Claim(BaseModel):
    """A single attributable statement. The atom of the whole report."""

    text: str = Field(min_length=1)
    source_ids: list[str] = Field(min_length=1, description="At least one. No exceptions.")
    confidence: Confidence = "medium"


class MetricPoint(BaseModel):
    period: str = Field(description="Fiscal period label, e.g. 'FY2025Q2' or 'FY2024'")
    value: float | None = Field(default=None, description="None means not reported")


class MetricSeries(BaseModel):
    """A financial time series, computed in Python — never estimated by the model."""

    key: str = Field(description="Stable machine key, e.g. 'revenue', 'gross_margin'")
    label: str
    unit: Literal["USD", "USD_millions", "percent", "ratio", "shares"]
    points: list[MetricPoint] = Field(min_length=1)
    source_ids: list[str] = Field(min_length=1)


class Section(BaseModel):
    kind: SectionKind
    title: str
    claims: list[Claim] = Field(default_factory=list)
    metrics: list[MetricSeries] = Field(default_factory=list)
    narrative_md: str = Field(
        default="",
        description="Optional prose tying the claims together. Any factual statement "
        "here must also appear as a Claim — the UI renders citations from claims.",
    )


class ReportMeta(BaseModel):
    """Run telemetry. Surfaced in the UI footer and consumed by the eval suite."""

    model: str = ""
    duration_seconds: float | None = None
    cost_usd: float | None = None
    tool_calls: int | None = None
    research_iterations: int | None = None


class Report(BaseModel):
    """A complete research report."""

    schema_version: str = SCHEMA_VERSION
    ticker: str = Field(pattern=r"^[A-Z.\-]{1,10}$")
    company_name: str
    question: str = Field(description="The user's question, or a generated one for ticker mode")
    generated_at: AwareDatetime
    data_as_of: AwareDatetime = Field(description="Freshness of the newest datapoint used")
    sections: list[Section] = Field(min_length=1)
    sources: list[Source] = Field(default_factory=list)
    meta: ReportMeta = Field(default_factory=ReportMeta)
    disclaimer: str = DISCLAIMER

    @model_validator(mode="after")
    def _no_duplicate_source_ids(self) -> Report:
        ids = [s.id for s in self.sources]
        duplicates = {i for i in ids if ids.count(i) > 1}
        if duplicates:
            raise ValueError(f"duplicate source ids: {sorted(duplicates)}")
        return self

    @model_validator(mode="after")
    def _no_dangling_citations(self) -> Report:
        known = {s.id for s in self.sources}
        missing: set[str] = set()
        for section in self.sections:
            for claim in section.claims:
                missing |= set(claim.source_ids) - known
            for series in section.metrics:
                missing |= set(series.source_ids) - known
        if missing:
            raise ValueError(
                f"claims cite unknown source ids: {sorted(missing)}. "
                "Every citation must resolve to an entry in Report.sources."
            )
        return self

    def source_by_id(self, source_id: str) -> Source | None:
        return next((s for s in self.sources if s.id == source_id), None)

    @property
    def claim_count(self) -> int:
        return sum(len(section.claims) for section in self.sections)


def export_json_schema() -> str:
    """JSON Schema for the report, used to generate TypeScript types for the web UI."""
    return json.dumps(Report.model_json_schema(), indent=2, ensure_ascii=False)
